# Generated by Django 2.2 on 2019-04-03 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_order_orderproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=6),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
        ),
    ]
